<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\HuntOnnxProbe.csproj" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime"
                      Version="1.28.0"
                      GeneratePathProperty="true" />
    <None Include="$(PkgMicrosoft_ML_OnnxRuntime)\runtimes\win-x64\native\onnxruntime.dll"
          Link="onnxruntime.dll"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
