<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net48;</TargetFrameworks>
        <RootNamespace>z3n7</RootNamespace>

    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="W:\code_hard\.net\z3n7\z3n7\z3n7.csproj" />
        <ProjectReference Include="W:\code_hard\.net\z3n7\z3n7.Captcha\z3n7.Captcha.csproj" />
        
    </ItemGroup>

    <ItemGroup>
    

    </ItemGroup>

    <ItemGroup>
        <Reference Include="ZennoLab.CommandCenter">
            <HintPath>c:\Program Files\ZennoLab\RU\ZennoPoster Pro V7\7.9.1.0\Progs\ZennoLab.CommandCenter.dll</HintPath>
        </Reference>
        <Reference Include="ZennoLab.InterfacesLibrary">
            <HintPath>c:\Program Files\ZennoLab\RU\ZennoPoster Pro V7\7.9.1.0\Progs\ZennoLab.InterfacesLibrary.dll</HintPath>
        </Reference>
    </ItemGroup>



</Project>
